name: http_cache_client
description: http cache client
version: 0.0.1
homepage: https://github.com/timfreiheit/http_cache_client

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  disk_lru_cache: ^0.0.2
  synchronized: ^2.1.1
  http: ^0.12.0+4

dev_dependencies:
  test: any
  pedantic: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
